#ifndef BSP_BOARD_CONFIG_H
#define BSP_BOARD_CONFIG_H
#include "hc32_ll.h"
#include "hc32_ll_gpio.h"
#define CONFIG_PERIPH_WE      (LL_PERIPH_GPIO | LL_PERIPH_EFM | LL_PERIPH_FCG | LL_PERIPH_PWC_CLK_RMU | LL_PERIPH_SRAM)
#define CONFIG_PERIPH_WP      (LL_PERIPH_FCG | LL_PERIPH_SRAM)
#define BSP_XTAL_PORT         GPIO_PORT_H
#define BSP_XTAL_PINS         (GPIO_PIN_00 | GPIO_PIN_01)
#define BSP_POWER_PORT        GPIO_PORT_B
#define BSP_POWER_PIN         GPIO_PIN_03
#define BSP_WATCHDOG_PORT     GPIO_PORT_A
#define BSP_WATCHDOG_PIN      GPIO_PIN_06
#define BSP_STATUS_LED_PORT   GPIO_PORT_B
#define BSP_STATUS_LED_PIN    GPIO_PIN_05
#define BSP_DEBUG_PSPCR_VALUE 0x03U
#endif
