#ifndef BSP_BOARD_CONFIG_H
#define BSP_BOARD_CONFIG_H

#include <stdint.h>

#define BOOT_POWER_HOLD_ACTIVE_LEVEL        1U
#define BOOT_EXTERNAL_WATCHDOG_IDLE_LEVEL   0U
#define BOOT_EXTERNAL_WATCHDOG_ACTIVE_LEVEL 1U
#define BOOT_EXTERNAL_WATCHDOG_INTERVAL_MS  3000U
#define BOOT_EXTERNAL_WATCHDOG_PULSE_MS     1U
#define BOOT_EXTERNAL_WATCHDOG_DEADLINE_MS  60000U
#define BOOT_STATUS_LED_ACTIVE_LEVEL        1U
#define BOOT_STATUS_LED_INACTIVE_LEVEL      0U
#define BOOT_DEBUG_PSPCR_VALUE              0x0003U

_Static_assert(BOOT_EXTERNAL_WATCHDOG_PULSE_MS > 0U, "watchdog pulse must be nonzero");
_Static_assert(BOOT_EXTERNAL_WATCHDOG_PULSE_MS < BOOT_EXTERNAL_WATCHDOG_INTERVAL_MS,
               "watchdog pulse must be shorter than its interval");
_Static_assert(BOOT_EXTERNAL_WATCHDOG_INTERVAL_MS < BOOT_EXTERNAL_WATCHDOG_DEADLINE_MS,
               "watchdog feed must precede the TPL5010 deadline");
_Static_assert(BOOT_EXTERNAL_WATCHDOG_IDLE_LEVEL != BOOT_EXTERNAL_WATCHDOG_ACTIVE_LEVEL, "watchdog levels must differ");
_Static_assert(BOOT_STATUS_LED_ACTIVE_LEVEL != BOOT_STATUS_LED_INACTIVE_LEVEL, "LED levels must differ");

#if !defined(BOOT_HOST_TEST)
#define CONFIG_PERIPH_WE            (LL_PERIPH_GPIO | LL_PERIPH_EFM | LL_PERIPH_FCG | LL_PERIPH_PWC_CLK_RMU | LL_PERIPH_SRAM)
#define CONFIG_PERIPH_WP            (LL_PERIPH_FCG | LL_PERIPH_SRAM)
#define BSP_XTAL_PORT               GPIO_PORT_H
#define BSP_XTAL_PINS               (GPIO_PIN_00 | GPIO_PIN_01)
#define BOOT_POWER_HOLD_PORT        GPIO_PORT_B
#define BOOT_POWER_HOLD_PIN         GPIO_PIN_03
#define BOOT_EXTERNAL_WATCHDOG_PORT GPIO_PORT_A
#define BOOT_EXTERNAL_WATCHDOG_PIN  GPIO_PIN_06
#define BOOT_STATUS_LED_PORT        GPIO_PORT_B
#define BOOT_STATUS_LED_PIN         GPIO_PIN_05
#define BOOT_I2C_UNIT               CM_I2C1
#define BOOT_I2C_CLOCK              FCG1_PERIPH_I2C1
#define BOOT_I2C_BAUDRATE           400000U
#define BOOT_I2C_SCL_TIME           5UL
#define BOOT_I2C_SCL_PORT           GPIO_PORT_A
#define BOOT_I2C_SCL_PIN            GPIO_PIN_03
#define BOOT_I2C_SCL_FUNC           GPIO_FUNC_49
#define BOOT_I2C_SDA_PORT           GPIO_PORT_A
#define BOOT_I2C_SDA_PIN            GPIO_PIN_02
#define BOOT_I2C_SDA_FUNC           GPIO_FUNC_48
#define BOOT_I2C_EEI_IRQn           INT005_IRQn
#define BOOT_I2C_RXI_IRQn           INT006_IRQn
#define BOOT_I2C_TEI_IRQn           INT004_IRQn
#define BOOT_I2C_EEI_SOURCE         INT_SRC_I2C1_EEI
#define BOOT_I2C_RXI_SOURCE         INT_SRC_I2C1_RXI
#define BOOT_I2C_TEI_SOURCE         INT_SRC_I2C1_TEI
#define BOOT_I2C_EEI_PRIORITY       DDL_IRQ_PRIO_09
#define BOOT_I2C_RXI_PRIORITY       DDL_IRQ_PRIO_10
#define BOOT_I2C_TEI_PRIORITY       DDL_IRQ_PRIO_10
#endif

#endif
