#ifndef BOOT_CONFIG_H
#define BOOT_CONFIG_H

#define BOOT_ENABLE_I2C_SLAVE        1
#define BOOT_ENABLE_LEGACY_PROTOCOL  1
#define BOOT_ENABLE_LEGACY_HANDSHAKE 1
#ifndef BOOT_ENABLE_LEGACY_ERASE
#define BOOT_ENABLE_LEGACY_ERASE 0
#endif
#ifndef BOOT_ENABLE_LEGACY_DOWNLOAD
#define BOOT_ENABLE_LEGACY_DOWNLOAD 0
#endif
#ifndef BOOT_ENABLE_LEGACY_JUMP
#define BOOT_ENABLE_LEGACY_JUMP 0
#endif
#define BOOT_ENABLE_LEGACY_UPLOAD 0
#ifndef BOOT_ENABLE_FLASH_UPDATE
#define BOOT_ENABLE_FLASH_UPDATE 0
#endif
#ifndef BOOT_ENABLE_LEGACY_UPDATE_SIMULATION
#define BOOT_ENABLE_LEGACY_UPDATE_SIMULATION 1
#endif
#ifndef BOOT_ENABLE_APPLICATION_JUMP
#define BOOT_ENABLE_APPLICATION_JUMP 1
#endif
#define BOOT_ENABLE_SOFTWARE_RESET_ENTRY 1
#ifndef BOOT_CFG_LOGGING
#define BOOT_CFG_LOGGING 1
#endif
#define BOOT_ENABLE_SEGGER_RTT             BOOT_CFG_LOGGING
#define BOOT_ENABLE_EASYLOGGER             BOOT_CFG_LOGGING
#define BOOT_ENABLE_DEBUG_LOG              BOOT_CFG_LOGGING
#define BOOT_ENABLE_STATUS_LED             1
#define BOOT_ENABLE_POWER_HOLD             1
#define BOOT_ENABLE_EXTERNAL_WATCHDOG      1
#define BOOT_ENABLE_HOST_TESTS             0

#define BOOT_I2C_SLAVE_ADDRESS             0x11U
#define BOOT_I2C_BUFFER_CAPACITY           544U
#define BOOT_PROTOCOL_PARTIAL_TIMEOUT_MS   250UL
#define BOOT_I2C_STALL_TIMEOUT_MS          2000UL
#define BOOT_APPLICATION_DATA_MAX          512U
#define BOOT_APPLICATION_HANDOVER_GUARD_MS 100UL
#define BOOT_UPDATE_WINDOW_MS              (10 * 60 * 1000UL)

#ifndef BOOT_BUILD_ID
#define BOOT_BUILD_ID "unknown"
#endif

#if BOOT_ENABLE_LEGACY_HANDSHAKE && !BOOT_ENABLE_LEGACY_PROTOCOL
#error "Legacy handshake requires legacy protocol"
#endif
#if BOOT_ENABLE_LEGACY_PROTOCOL && !BOOT_ENABLE_I2C_SLAVE
#error "Legacy protocol requires I2C slave"
#endif
#if (BOOT_ENABLE_LEGACY_ERASE || BOOT_ENABLE_LEGACY_DOWNLOAD) && !BOOT_ENABLE_FLASH_UPDATE
#error "Legacy erase/download require Flash update"
#endif
#if BOOT_ENABLE_LEGACY_JUMP && !BOOT_ENABLE_APPLICATION_JUMP
#error "Legacy jump requires application jump"
#endif
#if BOOT_ENABLE_LEGACY_UPDATE_SIMULATION && !BOOT_ENABLE_LEGACY_PROTOCOL
#error "Legacy simulation requires legacy protocol"
#endif

#endif
